nohup ./add-competition.sh &
nohup ./add-events.sh &
nohup ./add-market-types.sh &
nohup ./add-market-book-odds.sh &
nohup ./socket-add-competition.sh  &
nohup ./get-expired-fancy-data.sh  &
nohup ./socket-add-competition.sh  &
nohup ./socket-fancy-send.sh  &
nohup ./add-casino-ltp.sh &
nohup ./add-casino-7ud.sh &
nohup ./add-casino-ab.sh &
nohup  ./add-casino-t20.sh &
nohup  ./add-casino-dt20.sh &
nohup  ./add-casino-aaa.sh &
nohup  ./add-casino-32c.sh &
nohup ./casino-bet-settle.sh &
nohup ./send-casino-response.sh &
nohup ./casino-old-data-delete.sh &
nohup ./7ud-casino-bet-settle.sh &
nohup ./ltp-casino-bet-settle.sh &
nohup ./dt20-casino-bet-settle.sh &
nohup ./casino-score-data.sh &
